apiVersion: v1
kind: PersistentVolume
metadata:
  name: kube-data
spec:
  capacity:
    storage:
      10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: 
    nfs-pv
  nfs:
    server:
      192.168.0.10
    path:
      "/home/manager/nfs/shared"
