apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-configmap
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval:     5s
      evaluation_interval: 5s
    scrape_configs:
      - job_name: 'node-exporter1'
        static_configs:
        - targets: 
          - "192.168.0.11:9100"
          - "192.168.0.12:9100"
          - "192.168.0.13:9100"
          - "192.168.0.14:9100"
