apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitoring-data-2
spec:
  capacity:
    storage:
      1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: 
    grafana-nfs-pv
  nfs:
    server:
      192.168.0.10
    path:
      "/home/manager/nfs/shared/grafana"
