apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: monitoring
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9100'
spec:
  selector:
    app: node-exporter   # 노드 익스포터 파드를 식별하기 위한 셀렉터
  ports:
    - name: exporter-port
      protocol: TCP
      port: 9100         # 클러스터 ip에 바인딩되는 포트
      targetPort: 9100   # 파드의 실재 어플리케이션이 리스닝하는 포트
  type: NodePort
